services:
  - type: web
    name: crl-noise-backend
    env: node
    region: frankfurt
    plan: free

    rootDir: .
    buildCommand: "npm install"
    startCommand: "node server.mjs"

    autoDeploy: true

    envVars:
      NODE_VERSION: 20
      CHECKWX_KEY: {{ CHECKWX_KEY }}
      OPENWEATHER_KEY: {{ OPENWEATHER_KEY }}
      AIRLABS_KEY: {{ AIRLABS_KEY }}
      NOISE_API_BASE: {{ NOISE_API_BASE }}
