services:
  - type: web
    name: crl-noise-backend
    env: node
    region: frankfurt
    plan: free

    rootDir: backend-crl-noise
    buildCommand: "npm install"
    startCommand: "node server.mjs"

    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: CHECKWX_KEY
        value: ""
      - key: OPENWEATHER_KEY
        value: ""
      - key: AIRLABS_KEY
        value: ""
      - key: NOISE_API_BASE
        value: ""
